### ISSUE TITLE
create fully onchain split, get price, and trade smart contracts

### ISSUE THREAD

**Issue by cotraders** [1inch/limit-order-protocol#1]
A fully onchain DEX aggrator will allow DeFi building blocks for cotrader.com and others.

Prices should be competitive with other DEX aggregator options..

Users can get prices and execute a split trade that gets the max tokens possible at the lowest prices available by using a combination of dexs, especially AMM Swap DEXs including Kyber, Bancor, Uniswap, Oasis.

**Comment by galekseev** [comment]
Hi, thank you for your suggestion. For the feature you're describing, you might want to consider using the 1inch DApp. It not only aggregates prices from various DEXs, but also allows for optimized split trades to get the best rates.

Additionally, 1inch now offers an enterprise API which can be a great tool for integrations like this. You can find more details and access the API on the developer portal: [1inch Developer Portal](https://portal.1inch.dev/).
