### ISSUE TITLE
Websocket API for order updates

### ISSUE THREAD

**Issue by cgebe** [1inch/limit-order-protocol#163]
Is there a Websocket API for subscribing to order updates? 
Similar to: https://docs.0x.org/0x-api-orderbook/api-references/websocket-api

If it does not exist, would then request this feature.

**Comment by galekseev** [comment]
Thank you for your suggestion. We are pleased to inform you that we have implemented WebSocket API for Fusion mode swaps. This means that any fusion mode resolver can now receive updates using this feature. You can find more information on how to use it by visiting the following link: https://github.com/1inch/fusion-sdk/blob/main/src/ws-api/README.md

However, we regret to inform you that we will not be implementing WebSocket API support for regular limit orders. If you have any further suggestions or feedback, please do not hesitate to let us know.
