### ISSUE TITLE
Added Details for RFQ and Order Limit Differences

### ISSUE THREAD

**Issue by zodenode** [1inch/limit-order-protocol#233]
Creating Markdown to state the differences between Limit Order and RFQ

**Comment by galekseev** [comment]
Thank you for taking the time to submit your suggestion. We appreciate your contribution. Our team is currently working on improving documentation. If you have any further suggestions or feedback, please do not hesitate to let us know.

**Comment by zodenode** [comment]
Thanks for giving the swift feedback @galekseev
