### ISSUE TITLE
supports for signTypedData_v4 

### ISSUE THREAD

**Issue by everest2105** [1inch/limit-order-protocol#89]
Hi,

I'd like to make a limit order, with a wallet on Trezor (not using Metamask, as this seems to be not supported yet).
I get the error: 

The signing of a limit order in your wallet failed. Please, use another wallet that supports the method signTypedData_v4

Based on Trezor, this should now be supported also on Trezor ONE - since the firmware release in Jan.
Please see:
https://github.com/trezor/trezor-firmware/issues/2128 
and
https://github.com/trezor/trezor-firmware/pull/1970

Is this something you can solve on 1inch side? 
Thanks!

**Comment by shoom3301** [comment]
Hi @everest2105, we support typed data signing in our application app.1inch.io.
You can implement it using our library and trezor-connect lib:

https://github.com/trezor/connect/blob/develop/src/js/core/methods/EthereumSignTypedData.js

https://github.com/1inch/limit-order-protocol-utils/blob/master/docs/quick-start.md
>Note: you can use any implementation for the provider.
