### ISSUE TITLE
Token amounts aren't updated when taker = maker

### ISSUE THREAD

**Issue by ivanproskuryakov** [1inch/limit-order-protocol#91]
Is it possible to use your limit order protocol for the cases when both the maker and the taker are the same address?

I'm thinking about using it to accept crypto payments for the merchants. 
In my scenario, customers pay for products from the customer's wallet with the conversion of a token into stable coin in the background utilizing 1inch swap, with the following involvement of `order.interaction` API and withdrawal of stable coin into the merchant's wallet.

Following this Idea I'm trying to swap `eth` with `dai` assets but after all the balances aren't changing.
Cudl you take a look, please?

```js
expect(await this.weth.balanceOf(addr1)).not.to.be.bignumber.equal('1000000');
expect(await this.dai.balanceOf(addr1)).not.to.be.bignumber.equal('1000000');
```
See https://github.com/1inch/limit-order-protocol/pull/92 pull request opened with the test added.

**Comment by ZumZoom** [comment]
Why would they change? You send 1 weth and 1 dai to the same address so balances end up the same they were before the swap.

**Comment by ivanproskuryakov** [comment]
Hi, @ZumZoom thanks for joining me on this issue!
I'm confused, but even in the case of a single address, we swap ETH to DAI, which means we need to see updated numbers.

**Comment by Pzixel** [comment]
You're swapping 1 dai from addr1 to 1 weth on addr1. So how does swap work:
maker addr1 sends 1 dai to taker addr1
taker addr1 sends 1 weth to maker addr1

So addr1 which started with (1,1) ends with (1,1)
