### ISSUE TITLE
Bug: orders with old price

### ISSUE THREAD

**Issue by Kwaskoff** [1inch/limit-order-protocol#99]
I had very old order and I forgot about it 
![Screenshot from 2022-05-12 12-39-34](https://user-images.githubusercontent.com/15308024/168052991-98ae1814-17d8-47f7-a931-31b20f800d74.png)
Right now 1inch token price is 0.8 USDT.
USDT was not approved, and when I approved USDT - old orders was bought 1inch tokens for 1.25 USDT - Whaaat?
https://www.bscscan.com/tx/0xd74f7c98cae8cf3738868754cb53952ac3752a7a237ce8f8b0c76b1cc80f072e
https://www.bscscan.com/tx/0xd74f7c98cae8cf3738868754cb53952ac3752a7a237ce8f8b0c76b1cc80f072e

Pls, fix it in the protocol - don't buy tokens higher than market (amazing idea!).
And fix it in your interface - if I forgot about this orders, it can notify me before approving USDT.. I don't want buy 1inch token right now =)
Thanks, guys for your work!

**Comment by galekseev** [comment]
Hi. we appreciate your feedback and understand the frustration that can occur with old orders executing at non-current market rates. However, it's important to note that the protocol itself contains all the necessary features and won't be amended to address this issue.

Instead, this is something that should be resolved at the level of the DApp, where additional features and UI tools can be implemented to prevent such situations. You can check the [contact page](https://1inch.io/contacts/) to address the issue to the DApp team.

Thank you for your continued support.
